const fs=require('fs'),vm=require('vm'),assert=require('assert/strict');
const nodes=new Map();let registered,downloaded;
const document={querySelector:s=>{if(!nodes.has(s))nodes.set(s,{innerHTML:'',style:{},close(){},showModal(){}});return nodes.get(s)},querySelectorAll:()=>[],createElement:()=>({click(){}}),modelContext:{registerTool:t=>{registered=t}}};
const ctx=vm.createContext({document,console,setTimeout,crypto:require('crypto').webcrypto,ExcelJS:require('exceljs'),Blob,URL:{createObjectURL:b=>{downloaded=b;return 'blob:test'},revokeObjectURL(){}},fetch:async()=>({ok:false,status:401,json:async()=>({error:'로그인이 필요합니다.'})})});
vm.runInContext(fs.readFileSync('dist/app.js','utf8'),ctx);const run=s=>vm.runInContext(s,ctx);
(async()=>{
 await new Promise(r=>setImmediate(r));assert.ok(nodes.get('#app').innerHTML.includes('loginForm'));
 assert.equal(run('accounts.length'),0);assert.equal(run('events.length'),0);
 run("accounts=[{id:'admin',name:'관리자',role:'관리자',class:''},{id:'teacher.a',name:'교사',role:'교사',class:'면접 A반'},{id:'student.a',number:'30101',name:'학생',role:'학생',class:'면접 A반'}];user=accounts[0];identity=user.id;role=user.role;render();");
 assert.equal(nodes.get('#app').innerHTML.includes('화면 미리보기'),false);
 assert.ok(nodes.get('#app').innerHTML.includes('addUniversity'));
 await run('downloadTemplate()');let wb=new ctx.ExcelJS.Workbook();await wb.xlsx.load(await downloaded.arrayBuffer());
 assert.equal(wb.worksheets[0].getCell('C2').dataValidation.formulae[0],'"교사,학생"');assert.equal(wb.worksheets[0].getRow(1).getCell(5).text,'아이디');
 run("user=accounts[1];identity=user.id;role=user.role;render();");await run('downloadTemplate()');wb=new ctx.ExcelJS.Workbook();await wb.xlsx.load(await downloaded.arrayBuffer());
 assert.equal(wb.worksheets[0].getCell('C2').dataValidation.formulae[0],'"학생"');assert.equal(wb.worksheets[0].getCell('D2').value,'면접 A반');
 run("selected='student.a';events=[{id:'one',student:selected,type:'interview',univ:'테스트대',major:'학과',date:'2026-11-20',time:'10:00'},{id:'two',student:selected,type:'final',univ:'테스트대',major:'학과',date:'2026-12-05',time:'14:00'}];");
 const timeline=run('timelineView(visibleStudents())');assert.ok(timeline.indexOf('11월 20일')<timeline.indexOf('12월 5일'));assert.ok(timeline.includes('timeline-cell link'));assert.equal(timeline.includes('1차 합격자 발표'),false);
 assert.equal(run("esc('<img onerror=alert(1)>')"),'&lt;img onerror=alert(1)&gt;');
 run("user=accounts[0];identity=user.id;role=user.role;tab='accounts';accountRole='교사';render();");
 assert.ok(nodes.get('#app').innerHTML.includes('data-account-role="학생"'));assert.ok(nodes.get('#app').innerHTML.includes('data-edit-classes="teacher.a"'));assert.equal(nodes.get('#app').innerHTML.includes('data-delete-account="student.a"'),false);
 run("accountRole='학생';render();");assert.ok(nodes.get('#app').innerHTML.includes('data-delete-account="student.a"'));assert.equal(nodes.get('#app').innerHTML.includes('data-edit-classes="teacher.a"'),false);
 run("accounts[1].class='면접 A반, 면접 B반';accounts.push({id:'student.b',role:'학생',name:'B학생',class:'면접 B반'});user=accounts[1];identity=user.id;role=user.role;activeClass='면접 B반';render();");assert.equal(run('visibleStudents()[0].id'),'student.b');assert.ok(nodes.get('#app').innerHTML.includes('data-class="면접 A반"'));
 await run('downloadTemplate()');wb=new ctx.ExcelJS.Workbook();await wb.xlsx.load(await downloaded.arrayBuffer());assert.equal(wb.getWorksheet('배정반 목록').getCell('A2').value,'면접 B반');assert.equal(wb.worksheets[0].getCell('D2').value,'면접 B반');
 run("user=accounts[2];identity=user.id;role=user.role;render();");assert.equal(nodes.get('#app').innerHTML.includes('id="addLesson"'),false);assert.equal(nodes.get('#app').innerHTML.includes('data-tab="accounts"'),false);
 assert.ok(nodes.get('#app').innerHTML.includes('data-tab="applications"'));
 const entry=run('applicationsView()');assert.equal((entry.match(/data-application-row=/g)||[]).length,6);assert.ok(entry.includes('바로 면접 응시'));assert.ok(entry.includes('생기부 기반'));
 run("events.push({...events[0],id:'disabled',application:'student.a:0',inactive:true});selected=identity;");assert.ok(run('timelineView(visibleStudents())').includes('disabled aria-disabled="true"'));
 assert.ok(nodes.get('#app').innerHTML.includes('data-tab="resources"'));
 assert.equal(run('calendarView([])').includes('data-add-date='),false);
 run("role='교사';identity='teacher.a';");assert.ok(run('calendarView([])').includes('data-add-date='));
 run("resourcePosts=[{id:'abc',title:'<script>bad</script>',content:'x',author_name:'교사',created_at:'2026-09-12',files:[]}];");assert.ok(run('resourcesView()').includes('&lt;script&gt;bad&lt;/script&gt;'));
 run("role='학생';identity='student.a';availability=[{student:'student.a',days:[1,3],note:'<특이사항>'}];");assert.equal(run('resourcesView()').includes('id="writeResource"'),false);assert.ok(run('availabilityPanel(identity)').includes('&lt;특이사항&gt;'));assert.ok(run('applicationsView()').includes('방과후 일정 조정'));
 const shading=run(`(()=>{const classes=new Set(),checkbox={disabled:false,checked:true},message={textContent:''},label={dataset:{targetId:'student.a'},classList:{toggle:(c,on)=>on?classes.add(c):classes.delete(c)},querySelector:()=>message},date={value:'2026-11-09'},form={elements:{namedItem:()=>date},querySelectorAll:()=>[label]};shadeLessonTargets(form);const marked=classes.has('unavailable');date.value='2026-11-10';shadeLessonTargets(form);return {marked,cleared:!classes.has('unavailable'),disabled:checkbox.disabled,checked:checkbox.checked};})()`);assert.equal(shading.marked,true);assert.equal(shading.cleared,true);assert.equal(shading.disabled,false);assert.equal(shading.checked,true);
 run("role='교사';identity='teacher.a';showOtherTeachers=false;showUniversity=true;events=[{id:'own',type:'lesson',lesson_kind:'2차-개별지도',teacher_id:'teacher.a'},{id:'other',type:'lesson',lesson_kind:'2차-개별지도',teacher_id:'teacher.b'},{id:'ot',type:'lesson',lesson_kind:'1차-OT',teacher_id:'teacher.b'},{id:'mock',type:'lesson',lesson_kind:'3차-모의면접',teacher_id:'teacher.b'},{id:'college',type:'first'}];");assert.equal(run('filteredCalendarEvents(events).map(e=>e.id).join()'),'own,ot,mock,college');
 run('showOtherTeachers=true;');assert.equal(run('filteredCalendarEvents(events).length'),5);run('showUniversity=false;');assert.equal(run('filteredCalendarEvents(events).length'),4);run('showOtherTeachers=false;');assert.equal(run('filteredCalendarEvents(events).map(e=>e.id).join()'),'own,ot,mock');
 assert.ok(run("admissionResultForm({type:'first',application:'student.a:0',result:'합격'})").includes('selected>합격'));assert.equal(run("admissionResultForm({type:'interview'})"),'');assert.equal(run("admissionResultForm({type:'final',inactive:true})"),'');
 assert.equal(registered.name,'get_visible_interview_schedule');await assert.rejects(()=>registered.execute({unexpected:true}));await assert.rejects(()=>registered.execute({}),/로그인/);
 console.log('PASS: login rendering, role UI, timeline, XLSX dropdowns, and WebMCP rejection paths (VM; no browser visual QA)');
})().catch(e=>{console.error(e);process.exitCode=1});
